name: padim-anomaly-detection
channels:
  - conda-forge
dependencies:
  - python==3.7
  - ipykernel
  - ipython
  - matplotlib
  - pandas
  - scikit-learn
  - scikit-image
  - tqdm
  - jinja2
  - groff
  - boto3
  - sagemaker
  - awscli
  - xgboost
